const allergenList = {
    Alcohol : 'alcohol-free',
    Immune : 'immuno-supportive',
    Celery : 'celery-free',
    Crustacean: 'crustacean-free',
    Dairy : 'dairy-free',
    Eggs : 'egg-free',
    Fish : 'fish-free',
    FODMAP : 'fodmap-free',
    Gluten : 'gluten-free',
    Keto : 'keto-friendly',
    Kidney : 'kidney-friendly',
    Kosher : 'kosher',
    Potassium : 'low-potassium',
    Lupine : 'lupine-free',
    Mediterranean : 'Mediterranean',
    Mstard : 'mustard-free',
    Low_fat_abs : 'low-fat-abs',
    No_oil_added : 'No-oil-added',
    No_sugar : 'low-sugar',
    Paleo : 'paleo',
    Peanuts : 'peanut-free',
    Pescatarian : 'pecatarian',
    Pork : 'pork-free',
    Red_meat_free: 'red-meat-free',
    Sesame_free: 'sesame-free',
    Shellfish: 'shellfish-free',
    Soy: 'soy-free',
    Sugar: 'sugar-conscious',
    Tree_nuts: 'tree-nut-free',
    Vegan: 'vegan',
    Vegetarian: 'Vegetarian',
    Wheat_free : 'Wheat-free'
}

export default allergenList