const allergenList = {
    // Alcohol : 'alcohol-free',
    // Immune : 'immuno-supportive',
    Celery : 'celery',
    Crustacean: 'crustacean',
    Dairy : 'dairy',
    Eggs : 'egg',
    Fish : 'fish',
    FODMAP : 'fodmap',
    Gluten : 'gluten',
    // Keto : 'keto',
    Kidney : 'kidney',
    // Kosher : 'kosher',
    // Potassium : 'low-potassium',
    // Lupine : 'lupine-free',
    // Mediterranean : 'Mediterranean',
    Mstard : 'mustard',
    // Low_fat_abs : 'low-fat-abs',
    // No_oil_added : 'No-oil-added',
    // No_sugar : 'low-sugar',
    // Paleo : 'paleo',
    Peanuts : 'peanut',
    // Pescatarian : 'pecatarian',
    Pork : 'pork',
    // Red_meat_free: 'red-meat',
    Sesame_free: 'sesame',
    Shellfish: 'shellfish',
    Soy: 'soy',
    Sugar: 'sugar',
    Tree_nuts: 'tree-nut',
    // Vegan: 'vegan',
    // Vegetarian: 'Vegetarian',
    Wheat_free : 'Wheat'
}

export default allergenList